filebeat.autodiscover:
  providers:
   - type: docker
     hints.enabled: true
     templates:
      - condition:
          contains:
            docker.container.image: demo
        config:
          - type: container
            paths:
              - /var/lib/docker/containers/${data.docker.container.id}/*.log
            exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
            json.keys_under_root: true
            json.add_error_key: true
            json.message_key: message
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
